version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:14

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Start Docker daemon
          command: sudo service docker start

      - run:
          name: Build Docker image
          command: docker build -t wfliu66/docker-react -f Dockerfile.dev .

      - run:
          name: Run tests
          command: docker run -e CI=true wfliu66/docker-react npm run test
