version: 2
sudo: required
services:
  - docker

before_install:
  - docker build -t wfliu66/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wfliu66/docker-react npm run test


